on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  trigger_deploy:
    name: Trigger self-deploy via Deploy Monkey
    uses: distributhor/workflow-webhook@v3
    with:
      webhook_url: https://deploy.laurcons.ro/webhook/teamhex.spring/manual
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
    
